<?php
/** @var $changelog \NW\Model\Change[] */
?>
<?php include('Navigation.phtml') ?>
<h1>Profiili</h1>
<div class="ajax-form">
    <form action="/api/change-password/" method="post">
        <h3>Vaihda salasana</h3>
        <label><b>Vanha salasana:</b><input type="password" name="old-password"></label>
        <label><b>Uusi salasana:</b><input type="password" name="new-password"></label>
        <label><input type="submit" value="Vaihda"></label>
        <div id="error"></div>
    </form>
</div>