<?php
/** @var $feature \NW\Model\Feature */
?>
<?php include('Navigation.phtml') ?>
<h1>Muokkaa ominaisuutta</h1>
<p><a href="/admin/features/">&#8592;Takaisin ominaisuuksiin</a></p>
<div class="ajax-form">
    <form action="/admin/api/feature/update/" method="post">
        <h3>Lisää uusi ominaisuus</h3>
        <input type="hidden" name="id" value="<?= $feature->id() ?>">
        <label><b>Otsikko:</b><input class="wide" type="text" name="title" value="<?= $feature->title() ?>"></label>
        <label>
            <textarea name="description"><?= $feature->description() ?></textarea>
            <p><?= htmlspecialchars('Ainoat hyväksytyt html-tägit ovat <p>, <ul>, <li>, <b>, <i>',
                    ENT_QUOTES | ENT_HTML5) ?></p>
        </label>
        <label><input type="submit" value="Tallenna"></label>
    </form>
</div>