<h1>Sisäänkirjautuminen</h1>
<div class="ajax-form">
    <form action="/api/login/" method="post">
        <h3>Kirjaudu sisään</h3>
        <label><b>Käyttäjätunnus:</b><input type="text" name="username" maxlength="14"></label>
        <label><b>Salasana:</b><input type="password" name="password"></label>
        <label><input type="submit" value="Kirjaudu"></label>
        <div id="error"></div>
    </form>
</div>